import type { Destination, Package, Experience, Testimonial, JournalPost, Hotel } from './types';

export const destinations: Destination[] = [
  {
    id: 'santorini',
    name: 'Santorini',
    region: 'Cyclades',
    country: 'Greece',
    tagline: 'Cliffside villages above an impossibly blue sea',
    description:
      'Whitewashed villages cling to volcanic cliffs, where the light turns honey-gold at dusk and the Aegean stretches endlessly below. A sanctuary of quiet luxury and ancient beauty.',
    image: 'https://images.pexels.com/photos/161901/santorini-skyline-town-greece-161901.jpeg',
    gallery: [
      'https://images.pexels.com/photos/161901/santorini-skyline-town-greece-161901.jpeg',
      'https://images.pexels.com/photos/3224186/pexels-photo-3224186.jpeg',
      'https://images.pexels.com/photos/1450363/pexels-photo-1450363.jpeg',
      'https://images.pexels.com/photos/2110500/pexels-photo-2110500.jpeg',
    ],
    bestSeason: 'May — October',
    duration: '7 nights',
    priceFrom: 8400,
    rating: 4.9,
    experiences: ['Private sunset cruise', 'Caldera vineyard tasting', 'Cliffside yoga at dawn'],
    latitude: 36.3932,
    longitude: 25.4615,
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    region: 'Kansai',
    country: 'Japan',
    tagline: 'Ancient temples wrapped in mist and maple',
    description:
      'A thousand years of refinement distilled into moss gardens, wooden teahouses, and bamboo groves that whisper in the wind. Kyoto is silence made visible.',
    image: 'https://images.pexels.com/photos/161251/kyoto-temple-japan-161251.jpeg',
    gallery: [
      'https://images.pexels.com/photos/161251/kyoto-temple-japan-161251.jpeg',
      'https://images.pexels.com/photos/1440402/pexels-photo-1440402.jpeg',
      'https://images.pexels.com/photos/1408402/pexels-photo-1408402.jpeg',
      'https://images.pexels.com/photos/161253/kyoto-japan-temple-161253.jpeg',
    ],
    bestSeason: 'March — May, October — November',
    duration: '10 nights',
    priceFrom: 11200,
    rating: 5.0,
    experiences: ['Private tea ceremony', 'Dawn temple visit', 'Kaiseki with a master chef'],
    latitude: 35.0116,
    longitude: 135.7681,
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    region: 'Atlas',
    country: 'Morocco',
    tagline: 'A city of color, spice, and desert silence',
    description:
      'Riads hidden behind ochre walls, souks thick with saffron and leather, and the vast silence of the Sahara beyond. Marrakech overwhelms the senses, then rewards stillness.',
    image: 'https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg',
    gallery: [
      'https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg',
      'https://images.pexels.com/photos/631050/pexels-photo-631050.jpeg',
      'https://images.pexels.com/photos/1535607/pexels-photo-1535607.jpeg',
      'https://images.pexels.com/photos/2026342/pexels-photo-2026342.jpeg',
    ],
    bestSeason: 'October — April',
    duration: '8 nights',
    priceFrom: 7600,
    rating: 4.8,
    experiences: ['Atlas Mountain trek', 'Private riad dinner', 'Sahara overnight camp'],
    latitude: 31.6295,
    longitude: -7.9811,
  },
  {
    id: 'maldives',
    name: 'Maldives',
    region: 'Indian Ocean',
    country: 'Maldives',
    tagline: 'Overwater villas above a turquoise lagoon',
    description:
      'A string of coral atolls scattered across the equator, where the sand is white as bone and the water holds every shade of blue. Pure, weightless serenity.',
    image: 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg',
    gallery: [
      'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg',
      'https://images.pexels.com/photos/2422497/pexels-photo-2422497.jpeg',
      'https://images.pexels.com/photos/1287429/pexels-photo-1287429.jpeg',
      'https://images.pexels.com/photos/2613288/pexels-photo-2613288.jpeg',
    ],
    bestSeason: 'November — April',
    duration: '6 nights',
    priceFrom: 13800,
    rating: 4.9,
    experiences: ['Private sandbank picnic', 'Bioluminescent night dive', 'Spa over the lagoon'],
    latitude: 3.2028,
    longitude: 73.2207,
  },
  {
    id: 'patagonia',
    name: 'Patagonia',
    region: 'Andes',
    country: 'Argentina',
    tagline: 'Granite spires and glaciers at the end of the earth',
    description:
      'A wild, windswept land of jagged peaks, turquoise lakes, and glaciers that groan and calve into the water. Patagonia is nature at its most sublime and indifferent.',
    image: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    gallery: [
      'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
      'https://images.pexels.com/photos/1761273/pexels-photo-1761273.jpeg',
      'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg',
      'https://images.pexels.com/photos/1761298/pexels-photo-1761298.jpeg',
    ],
    bestSeason: 'November — March',
    duration: '12 nights',
    priceFrom: 15400,
    rating: 4.9,
    experiences: ['Glacier ice trek', 'Estancia stay with gauchos', 'Condor watching at dawn'],
    latitude: -49.3273,
    longitude: -72.8877,
  },
  {
    id: 'tuscany',
    name: 'Tuscany',
    region: 'Central Italy',
    country: 'Italy',
    tagline: 'Rolling hills, cypress roads, and Renaissance light',
    description:
      'A landscape that seems painted by a Renaissance hand — golden hills, stone farmhouses, and vineyards that produce some of the world’s most celebrated wines.',
    image: 'https://images.pexels.com/photos/162699/vine-vineyard-landscape-tuscany-162699.jpeg',
    gallery: [
      'https://images.pexels.com/photos/162699/vine-vineyard-landscape-tuscany-162699.jpeg',
      'https://images.pexels.com/photos/2070033/pexels-photo-2070033.jpeg',
      'https://images.pexels.com/photos/162696/vine-vineyard-landscape-tuscany-162696.jpeg',
      'https://images.pexels.com/photos/162698/vine-vineyard-landscape-tuscany-162698.jpeg',
    ],
    bestSeason: 'April — June, September — October',
    duration: '9 nights',
    priceFrom: 9800,
    rating: 4.8,
    experiences: ['Private wine estate tour', 'Truffle hunt in autumn', 'Cooking with a nonna'],
    latitude: 43.4,
    longitude: 11.0,
  },
];

export const packages: Package[] = [
  {
    id: 'aegean-escape',
    title: 'Aegean Escape',
    destination: 'Santorini, Greece',
    description:
      'Seven nights of cliffside serenity, private cruises, and curated tastings across the Cyclades.',
    image: 'https://images.pexels.com/photos/161901/santorini-skyline-town-greece-161901.jpeg',
    days: 8,
    nights: 7,
    priceFrom: 8400,
    inclusions: ['Private villa with caldera view', 'Daily breakfast & two dinners', 'Sunset cruise with chef', 'Vineyard tasting experience', 'Airport transfers', 'Personal concierge'],
    itinerary: [
      { day: 1, title: 'Arrival in Oia', detail: 'Private transfer to your cliffside villa. Welcome dinner under the stars.' },
      { day: 2, title: 'Caldera Exploration', detail: 'Guided walk through Oia and Fira. Sunset at the Akrotiri lighthouse.' },
      { day: 3, title: 'Private Sail', detail: 'Full-day catamaran cruise to red beach, hot springs, and Thirassia.' },
      { day: 4, title: 'Wine & Dine', detail: 'Visit three volcanic vineyards. Private tasting menu at a caldera-edge restaurant.' },
      { day: 5, title: 'Island Day', detail: 'Free day with optional spa, cooking class, or beach club.' },
      { day: 6, title: 'Dawn Yoga & Art', detail: 'Cliffside yoga at sunrise. Private studio visit with a local artist.' },
      { day: 7, title: 'Farewell', detail: 'Final sunset cruise. Late checkout and private transfer.' },
    ],
    rating: 4.9,
    tag: 'Signature',
  },
  {
    id: 'kyoto-essence',
    title: 'Kyoto Essence',
    destination: 'Kyoto, Japan',
    description:
      'Ten days among temples, tea masters, and the quiet discipline of Japanese craft.',
    image: 'https://images.pexels.com/photos/161251/kyoto-temple-japan-161251.jpeg',
    days: 11,
    nights: 10,
    priceFrom: 11200,
    inclusions: ['Ryokan & luxury hotel stays', 'Daily breakfast', 'Private tea ceremony', 'Kaiseki dinner experience', 'Bullet train transfers', 'English-speaking guide', 'Temple entry passes'],
    itinerary: [
      { day: 1, title: 'Arrival in Kyoto', detail: 'Private transfer to your ryokan. Welcome kaiseki dinner.' },
      { day: 2, title: 'Eastern Temples', detail: 'Kiyomizu-dera, Yasaka shrine, and the lanes of Gion at dusk.' },
      { day: 3, title: 'Arashiyama', detail: 'Bamboo grove at dawn, Tenryu-ji garden, and a riverside lunch.' },
      { day: 4, title: 'Tea & Craft', detail: 'Private tea ceremony. Visit to a Nishijin textile workshop.' },
      { day: 5, title: 'Nara Day Trip', detail: 'Todai-ji and the deer park. Return for a quiet evening.' },
      { day: 6, title: 'Philosopher’s Path', detail: 'Ginkaku-ji to Nanzen-ji. Afternoon at a private garden.' },
      { day: 7, title: 'Kibune & Kurama', detail: 'Mountain temple hike. Riverside dinner at a ryokan.' },
      { day: 8, title: 'Free Day', detail: 'Optional cooking class, shopping, or a sake tasting.' },
      { day: 9, title: 'Daitoku-ji', detail: 'Zen temples and a matcha ceremony with a master.' },
      { day: 10, title: 'Farewell', detail: 'Final morning at leisure. Private transfer to Osaka.' },
    ],
    rating: 5.0,
    tag: 'Signature',
  },
  {
    id: 'saharan-odyssey',
    title: 'Saharan Odyssey',
    destination: 'Marrakech, Morocco',
    description:
      'Eight nights from ochre-walled medina to the deep silence of the dunes.',
    image: 'https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg',
    days: 9,
    nights: 8,
    priceFrom: 7600,
    inclusions: ['Boutique riad & desert camp', 'Daily breakfast & three dinners', 'Atlas Mountain trek', 'Sahara overnight camp', 'Camel trek at sunset', 'Private 4×4 with driver-guide', 'Airport transfers'],
    itinerary: [
      { day: 1, title: 'Arrival in Marrakech', detail: 'Settle into your riad. Evening in the Jemaa el-Fnaa square.' },
      { day: 2, title: 'Medina Walk', detail: 'Guided souk tour, Bahia Palace, and a rooftop dinner.' },
      { day: 3, title: 'Atlas Mountains', detail: 'Drive to the High Atlas. Berber village walk and lunch.' },
      { day: 4, title: 'Aït Benhaddou', detail: 'Through the Tizi n’Tichka pass to the famed kasbah.' },
      { day: 5, title: 'Dades & Todra', detail: 'Gorges, palmeries, and an evening under the stars.' },
      { day: 6, title: 'Into the Sahara', detail: 'Camel trek to your desert camp. Sunset over the dunes.' },
      { day: 7, title: 'Return to Marrakech', detail: 'Long drive back with stops along the way.' },
      { day: 8, title: 'Farewell', detail: 'Hammam spa, last shopping, and a farewell dinner.' },
    ],
    rating: 4.8,
    tag: 'Adventure',
  },
  {
    id: 'lagoon-serenity',
    title: 'Lagoon Serenity',
    destination: 'Maldives',
    description:
      'Six nights in an overwater villa above a private turquoise lagoon.',
    image: 'https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg',
    days: 7,
    nights: 6,
    priceFrom: 13800,
    inclusions: ['Overwater villa', 'All meals & select beverages', 'Private sandbank picnic', 'Sunset dolphin cruise', 'Spa treatments daily', 'Snorkeling & dive excursions', 'Speedboat transfers'],
    itinerary: [
      { day: 1, title: 'Arrival', detail: 'Speedboat to your resort. Welcome champagne at sunset.' },
      { day: 2, title: 'Lagoon Day', detail: 'Guided snorkel of the house reef. Spa treatment.' },
      { day: 3, title: 'Sandbank Picnic', detail: 'Private boat to a deserted sandbank. Champagne lunch.' },
      { day: 4, title: 'Dolphin Cruise', detail: 'Sunset cruise to spot spinner dolphins.' },
      { day: 5, title: 'Dive or Dream', detail: 'Optional morning dive. Afternoon at the spa.' },
      { day: 6, title: 'Farewell', detail: 'Final swim. Speedboat transfer to Malé.' },
    ],
    rating: 4.9,
    tag: 'Indulgence',
  },
  {
    id: 'end-of-earth',
    title: 'End of the Earth',
    destination: 'Patagonia, Argentina',
    description:
      'Twelve nights of granite spires, advancing glaciers, and gaucho hospitality.',
    image: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    days: 13,
    nights: 12,
    priceFrom: 15400,
    inclusions: ['Lodge & estancia stays', 'All meals & house beverages', 'Glacier ice trek', 'Estancia experience', 'Private guide & 4×4', 'Internal flights', 'National park fees'],
    itinerary: [
      { day: 1, title: 'Arrival in El Calafate', detail: 'Settle into your lodge. Dinner with a view of Lago Argentino.' },
      { day: 2, title: 'Perito Moreno', detail: 'Walk the glacier balconies. Afternoon ice trek with crampons.' },
      { day: 3, title: 'Estancia Day', detail: 'Gaucho life, horseback ride, and a traditional asado.' },
      { day: 4, title: 'To El Chaltén', detail: 'Drive north. Afternoon walk to Laguna Capri.' },
      { day: 5, title: 'Fitz Roy Trek', detail: 'Full-day hike to the base of Cerro Fitz Roy.' },
      { day: 6, title: 'Laguna Torre', detail: 'Hike to Laguna Torre and the Maestri viewpoint.' },
      { day: 7, title: 'Rest Day', detail: 'Optional climbing clinic or a day at leisure.' },
      { day: 8, title: 'Cross to Chile', detail: 'Drive to Torres del Paine. Welcome to the park.' },
      { day: 9, title: 'Base Towers', detail: 'The classic trek to the Torres del Paine lookout.' },
      { day: 10, title: 'French Valley', detail: 'Hike into the hanging glaciers of the Valle del Francés.' },
      { day: 11, title: 'Grey Glacier', detail: 'Boat to the glacier face. Afternoon kayak option.' },
      { day: 12, title: 'Return', detail: 'Drive back to El Calafate. Farewell dinner.' },
    ],
    rating: 4.9,
    tag: 'Adventure',
  },
  {
    id: 'tuscan-dreams',
    title: 'Tuscan Dreams',
    destination: 'Tuscany, Italy',
    description:
      'Nine nights among vineyards, hill towns, and the warm light of the Renaissance.',
    image: 'https://images.pexels.com/photos/162699/vine-vineyard-landscape-tuscany-162699.jpeg',
    days: 10,
    nights: 9,
    priceFrom: 9800,
    inclusions: ['Villa & boutique hotel stays', 'Daily breakfast & three dinners', 'Private wine estate tours', 'Truffle hunt experience', 'Cooking class', 'Private driver-guide', 'Museum & cellar entries'],
    itinerary: [
      { day: 1, title: 'Arrival in Florence', detail: 'Settle into your villa in the Chianti hills. Welcome dinner.' },
      { day: 2, title: 'Florence', detail: 'Guided walk of the Duomo, Uffizi, and Oltrarno workshops.' },
      { day: 3, title: 'Chianti Road', detail: 'Visit two wine estates. Lunch at a family fattoria.' },
      { day: 4, title: 'Siena & San Gimignano', detail: 'Medieval towers, the Piazza del Campo, and gelato.' },
      { day: 5, title: 'Val d’Orcia', detail: 'The iconic cypress roads. Hot springs at Bagno Vignoni.' },
      { day: 6, title: 'Pienza & Montepulciano', detail: 'Pecorino tasting, wine cellars, and Renaissance ideals.' },
      { day: 7, title: 'Truffle Hunt', detail: 'Morning in the woods with a tartufaio. Cooking class after.' },
      { day: 8, title: 'Lucca & Pisa', detail: 'Bike the walls of Lucca. Afternoon at the leaning tower.' },
      { day: 9, title: 'Farewell', detail: 'Final dinner at your villa with local wines.' },
    ],
    rating: 4.8,
    tag: 'Signature',
  },
];

export const experiences: Experience[] = [
  {
    id: 'private-guides',
    title: 'Private Guides',
    description: 'Local scholars, chefs, and artists who open doors that remain closed to others.',
    icon: 'Compass',
    image: 'https://images.pexels.com/photos/1058959/pexels-photo-1058959.jpeg',
  },
  {
    id: 'curated-stays',
    title: 'Curated Stays',
    description: 'Villas, ryokans, and desert camps chosen for soul, not for stars.',
    icon: 'Home',
    image: 'https://images.pexels.com/photos/261101/pexels-photo-261101.jpeg',
  },
  {
    id: 'seamless-logistics',
    title: 'Seamless Logistics',
    description: 'Every transfer, ticket, and reservation handled before you arrive.',
    icon: 'Plane',
    image: 'https://images.pexels.com/photos/2026324/pexels-photo-2026324.jpeg',
  },
  {
    id: 'concierge',
    title: '24/7 Concierge',
    description: 'A single point of contact, from the first idea to the final farewell.',
    icon: 'ConciergeBell',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Eleanor Voss',
    role: 'Art Dealer',
    location: 'London',
    quote:
      'They understood the trip I wanted before I could articulate it. Every detail was so quietly perfect that I forgot anyone had arranged it at all.',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    rating: 5,
  },
  {
    id: '2',
    name: 'Marcus Aldridge',
    role: 'Architect',
    location: 'New York',
    quote:
      'The Kyoto journey changed how I think about space and silence. The access they arranged — private temples, a tea master’s home — was beyond imagination.',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg',
    rating: 5,
  },
  {
    id: '3',
    name: 'Sofia Marchetti',
    role: 'Vintner',
    location: 'Milan',
    quote:
      'I have traveled widely and rarely felt cared for like this. The Patagonia trek was wild and raw, yet we never wanted for anything.',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
    rating: 5,
  },
  {
    id: '4',
    name: 'James Holloway',
    role: 'Surgeon',
    location: 'Sydney',
    quote:
      'Booking was effortless, the journey was flawless, and the memories are indelible. This is how travel should feel — rare, personal, and entirely your own.',
    avatar: 'https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg',
    rating: 5,
  },
];

export const journalPosts: JournalPost[] = [
  {
    id: 'art-of-slow-travel',
    title: 'The Art of Slow Travel',
    excerpt: 'Why the most luxurious thing you can do on holiday is nothing at all — and how to do it well.',
    category: 'Philosophy',
    date: 'June 14, 2025',
    readTime: '6 min',
    image: 'https://images.pexels.com/photos/3601456/pexels-photo-3601456.jpeg',
    author: 'Camille Renaud',
    content:
      'There is a particular kind of stillness that only travel can reveal — the moment when the noise of daily life finally falls away and you are left with the sound of wind through cypress trees, or the slow turn of a prayer wheel. Slow travel is not about doing less; it is about noticing more. It is the difference between visiting a place and being briefly inhabited by it.\n\nWe have come to treat itineraries as checklists, as if a destination were a box to tick. But the most memorable moments are almost never the ones we planned. They are the unplanned coffee in a square no guidebook mentions, the conversation with a shopkeeper, the hour lost to a view that asked nothing of us.\n\nThe luxury of slow travel is the luxury of time — unstructured, unscheduled, unproductive. It is, perhaps, the rarest luxury left.',
  },
  {
    id: 'kyoto-in-autumn',
    title: 'Kyoto in Autumn: A Field Guide',
    excerpt: 'The temples, the gardens, and the quiet corners where the maple turns first.',
    category: 'Destinations',
    date: 'May 28, 2025',
    readTime: '8 min',
    image: 'https://images.pexels.com/photos/1408402/pexels-photo-1408402.jpeg',
    author: 'Hiroshi Tanaka',
    content:
      'Autumn in Kyoto is a slow burning. The maples do not turn all at once but in sequence — first the high mountain temples, then the gardens along the Philosopher’s Path, and finally the city itself. To time it right is to chase a wave of color down from the hills.\n\nBegin at Kiyomizu-dera at dawn, before the crowds. Walk down through Sannenzaka to Gion. Take tea at a quiet teahouse. In the afternoon, go to Tofuku-ji for its maples — the most photographed in the city, and worth every frame.\n\nThe secret is not the temples but the spaces between them: the moss gardens, the stone paths, the sound of water. Kyoto teaches you to listen.',
  },
  {
    id: 'packing-light',
    title: 'On Packing Light, and Well',
    excerpt: 'A capsule wardrobe for two weeks, three climates, and one carry-on.',
    category: 'Craft',
    date: 'April 12, 2025',
    readTime: '5 min',
    image: 'https://images.pexels.com/photos/1051073/pexels-photo-1051073.jpeg',
    author: 'Camille Renaud',
    content:
      'The art of packing is the art of editing. Choose a palette — three colors, no more. Build around a single jacket that works from city to trail. Add layers, not options.\n\nA good packing list is not about what you bring but about what you leave behind. The freedom of a single bag is, in the end, the freedom to move through the world unencumbered.',
  },
  {
    id: 'sahara-at-night',
    title: 'The Sahara at Night',
    excerpt: 'On silence, stars, and the particular loneliness of the desert.',
    category: 'Reflections',
    date: 'March 3, 2025',
    readTime: '4 min',
    image: 'https://images.pexels.com/photos/2026342/pexels-photo-2026342.jpeg',
    author: 'Yasmine El-Idrissi',
    content:
      'In the desert, the night is not dark but deep. The stars do not twinkle — they hold steady, as if pinned to the sky. The silence is not the absence of sound but the presence of something vast and attentive.\n\nTo sleep in the Sahara is to sleep at the edge of the world. You wake to a horizon unbroken by anything human, and for a moment you understand how small your life is, and how much of it is made by other people.',
  },
];

export const hotels: Hotel[] = [
  {
    id: 'h1',
    name: 'Canaves Oia Suites',
    destination: 'Santorini, Greece',
    image: 'https://images.pexels.com/photos/3224186/pexels-photo-3224186.jpeg',
    rating: 4.9,
    amenities: ['Caldera view', 'Infinity pool', 'Butler service'],
    priceFrom: 1200,
  },
  {
    id: 'h2',
    name: 'Hiiragiya Ryokan',
    destination: 'Kyoto, Japan',
    image: 'https://images.pexels.com/photos/1440402/pexels-photo-1440402.jpeg',
    rating: 5.0,
    amenities: ['Tatami suites', 'Kaiseki dining', 'Garden onsen'],
    priceFrom: 980,
  },
  {
    id: 'h3',
    name: 'Royal Mansour',
    destination: 'Marrakech, Morocco',
    image: 'https://images.pexels.com/photos/631050/pexels-photo-631050.jpeg',
    rating: 4.9,
    amenities: ['Private riads', 'Hammam spa', 'Rooftop dining'],
    priceFrom: 1100,
  },
  {
    id: 'h4',
    name: 'Soneva Fushi',
    destination: 'Maldives',
    image: 'https://images.pexels.com/photos/2422497/pexels-photo-2422497.jpeg',
    rating: 5.0,
    amenities: ['Overwater villa', 'Private pool', 'Observatory'],
    priceFrom: 2400,
  },
];

export const navLinks = [
  { label: 'Home', path: '/' },
  { label: 'Destinations', path: '/destinations' },
  { label: 'Packages', path: '/packages' },
  { label: 'Journal', path: '/blog' },
  { label: 'About', path: '/about' },
  { label: 'Contact', path: '/contact' },
];
